import { NextRequest, NextResponse } from "next/server";
import { getRequestAuth } from "@/lib/auth/requestAuth";
import { writeAuditLog } from "@/lib/server/auditLog";
import { getPaymentProvider } from "@/lib/payments/paymentService";
import { SubscriptionPlanId } from "@/lib/payments/PaymentProvider";
import { findRecentPendingOrder, insertSubscriptionOrder } from "@/lib/server/subscriptionRepository";

export const runtime = "nodejs";

// Demo INR pricing (Phase 6 scope) — a real pricing plan comes later.
const PLAN_PRICING_INR: Record<SubscriptionPlanId, number> = {
  premium_monthly: 199,
  premium_yearly: 1999,
};

const RECENT_ORDER_DEDUPE_WINDOW_MS = 2 * 60 * 1000;

function isValidPlan(value: unknown): value is SubscriptionPlanId {
  return value === "premium_monthly" || value === "premium_yearly";
}

export async function POST(request: NextRequest) {
  try {
    const auth = await getRequestAuth(request);
    if (!auth) {
      return NextResponse.json({ ok: false, error: "unauthorized" }, { status: 401 });
    }

    const body = await request.json().catch(() => ({}));
    const plan = body?.plan;
    if (!isValidPlan(plan)) {
      return NextResponse.json({ ok: false, error: "invalid_plan" }, { status: 400 });
    }

    // Reuse a recent pending order instead of creating a fresh Cashfree
    // order on every retry/double-click — Cashfree rejects a second
    // create-order call with a duplicate order_id (409), so re-fetching the
    // existing order's still-live payment_session_id is the only way to
    // resume it, not re-creating.
    const provider = getPaymentProvider();
    const existing = await findRecentPendingOrder(auth.userId, plan, RECENT_ORDER_DEDUPE_WINDOW_MS);
    if (existing) {
      const status = await provider.getOrderStatus(existing.provider_order_id);
      if (status.status === "pending" && status.paymentSessionId) {
        return NextResponse.json({
          ok: true,
          orderId: existing.provider_order_id,
          paymentSessionId: status.paymentSessionId,
          amountInr: existing.amount_inr,
        });
      }
    }

    const amountInr = PLAN_PRICING_INR[plan];
    const orderId = `sub_${auth.userId.slice(0, 8)}_${plan}_${Date.now()}`;

    // orderId is generated by us, not Cashfree, so the real value is already
    // known here — no placeholder/substitution syntax needed (Cashfree's
    // docs just recommend embedding order_id directly: "construct the URL
    // with the actual order ID value").
    const returnUrl = new URL("/upgrade/success", request.url);
    returnUrl.searchParams.set("order_id", orderId);

    const created = await provider.createOrder({
      orderId,
      amountInr,
      customerId: auth.userId,
      customerEmail: auth.name,
      returnUrl: returnUrl.toString(),
    });

    await insertSubscriptionOrder({
      userId: auth.userId,
      plan,
      providerOrderId: created.providerOrderId,
      amountInr,
    });

    await writeAuditLog({ action: "billing.create_order", userId: auth.userId, ok: true, route: "/api/billing/create-order", detail: plan });

    return NextResponse.json({
      ok: true,
      orderId: created.providerOrderId,
      paymentSessionId: created.paymentSessionId,
      amountInr,
    });
  } catch (error) {
    console.error("[billing.create_order] unhandled_error", {
      message: error instanceof Error ? error.message : "unknown_error",
    });
    return NextResponse.json({ ok: false, error: "create_order_failed" }, { status: 500 });
  }
}
