import { CategoryId } from "@/lib/questions";
import { ProtocolToleranceMode } from "@/lib/protocolTemplates";

export type ProductIngredient = {
  name: string;
  concentration: string;
  purpose: string;
};

export type ClinicalDemoProduct = {
  id: string;
  category: CategoryId;
  name: string;
  ingredients: ProductIngredient[];
  description: string;
  why: string;
  usage: string;
  priceInr: number;
  benefits: string[];
  shopifyHandle: string;
  tierLabel: string;
  suitableLevels: ProtocolToleranceMode[];
  keywords: string[];
  suitableSeverity: {
    min: number;
    max: number;
    label: string;
  };
  suitableSkinOrHairType: string[];
  compatibleProducts: string[];
  incompatibleProducts: string[];
  applicationMethod: string;
  quantity: string;
  frequency: string;
  targetArea: string;
  precautions: string[];
  storage: string;
  expectedTimeline: string;
  expectedBenefit: string;
  faq: Array<{ question: string; answer: string }>;
  evidenceLevel: "clinical" | "established" | "anecdotal";
  version: string;
};

export const clinicalDemoProductCatalog: Record<CategoryId, ClinicalDemoProduct[]> = {
  acne: [
    {
      id: "demo-acne-clear-serum",
      category: "acne",
      name: "Clear Reset Niacinamide Serum",
      ingredients: [
        { name: "Niacinamide", concentration: "5%", purpose: "Oil regulation and redness support" },
        { name: "Zinc PCA", concentration: "2%", purpose: "Sebum control and comfort" },
      ],
      description: "Daily balancing serum for oil-prone acne routines.",
      why: "Supports oil control, visible redness reduction, and better barrier tolerance.",
      usage: "Apply in the morning after cleansing and before moisturizer.",
      priceInr: 649,
      benefits: ["Oil balance", "Redness control", "Pore support"],
      shopifyHandle: "clear-reset-niacinamide-serum",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["niacinamide", "balancing", "morning", "oil", "serum"],
      suitableSeverity: { min: 0, max: 100, label: "All acne severities" },
      suitableSkinOrHairType: ["oily", "combination", "acne-prone"],
      compatibleProducts: ["demo-acne-bha-gel"],
      incompatibleProducts: [],
      applicationMethod: "Apply 2-3 drops with fingertips using gentle tapping motions",
      quantity: "2-3 drops",
      frequency: "Once daily in morning routine",
      targetArea: "Face and acne-prone zones",
      precautions: ["Patch test first", "Avoid eye area", "Use SPF during day"],
      storage: "Store at room temperature away from direct sunlight",
      expectedTimeline: "Visible oil reduction and comfort in 1-2 weeks",
      expectedBenefit: "Better oil balance and reduced irritation baseline",
      faq: [
        { question: "Can I use this with other actives?", answer: "Use with caution. Start with niacinamide alone, then introduce BHA or other actives separately." },
        { question: "Is this suitable for sensitive acne skin?", answer: "Yes. Niacinamide is gentle and suitable even for beginner tolerance levels." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
    {
      id: "demo-acne-bha-gel",
      category: "acne",
      name: "Pore Control BHA Gel",
      ingredients: [
        { name: "Salicylic Acid", concentration: "2%", purpose: "Exfoliation and pore clearing" },
        { name: "Willow Bark Extract", concentration: "1%", purpose: "Anti-inflammatory support" },
      ],
      description: "Night treatment gel for clogged pores and recurring breakouts.",
      why: "Clears pore buildup and lowers breakout recurrence when used steadily.",
      usage: "Use on alternate nights, then increase if tolerated.",
      priceInr: 699,
      benefits: ["Pore clearing", "Breakout control", "Texture support"],
      shopifyHandle: "pore-control-bha-gel",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["salicylic", "bha", "night", "treatment", "active"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high acne" },
      suitableSkinOrHairType: ["oily", "combination"],
      compatibleProducts: ["demo-acne-clear-serum"],
      incompatibleProducts: [],
      applicationMethod: "Apply thin even layer to entire acne-prone area after cleansing",
      quantity: "Pea-sized",
      frequency: "Every other night, then nightly if tolerated",
      targetArea: "Face and acne-prone zones",
      precautions: ["Start slowly on alternate nights", "Use SPF 30+ daily", "Do not use with other exfoliants initially"],
      storage: "Store in cool, dry place. Avoid direct sunlight.",
      expectedTimeline: "Reduced congestion in 3-7 days, clear pore improvement in 2-4 weeks",
      expectedBenefit: "Lower recurring breakout frequency and smoother texture",
      faq: [
        { question: "Can I use daily from day 1?", answer: "No. Start on alternate nights. Increase to daily only after 2 weeks if skin tolerates well." },
        { question: "Should I moisturize after this?", answer: "Yes, always use a gentle moisturizer after BHA to maintain barrier integrity." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
  ],
  hair_loss: [
    {
      id: "demo-hair-growth-serum",
      category: "hair_loss",
      name: "Follicle Activate Growth Serum",
      ingredients: [
        { name: "Redensyl", concentration: "0.75%", purpose: "Follicle activation and density support" },
        { name: "Peptide Complex", concentration: "2%", purpose: "Growth signaling and scalp conditioning" },
      ],
      description: "Scalp serum for thinning zones and daily density support.",
      why: "Supports a consistent growth-focused routine on hairline and crown areas.",
      usage: "Apply to dry scalp partitions each morning or night as directed.",
      priceInr: 999,
      benefits: ["Density support", "Scalp consistency", "Follicle care"],
      shopifyHandle: "follicle-activate-growth-serum",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["growth", "serum", "follicle", "topical", "scalp"],
      suitableSeverity: { min: 0, max: 100, label: "All hair loss severities" },
      suitableSkinOrHairType: ["all hair types"],
      compatibleProducts: ["demo-hair-keto-shampoo"],
      incompatibleProducts: [],
      applicationMethod: "Parting hair and applying directly to scalp with applicator or fingertips",
      quantity: "5-10 drops or as labeled",
      frequency: "Once or twice daily",
      targetArea: "Scalp partitions, hairline, crown, thinning zones",
      precautions: ["Avoid scalp irritation", "Wait 5 minutes before using other scalp products", "Do not apply to wet hair"],
      storage: "Store in cool, dark place. Shelf life 12 months after opening.",
      expectedTimeline: "Improved scalp feel in 2-3 weeks, visible density changes in 8-12 weeks",
      expectedBenefit: "Steadier follicle environment and visibly denser-appearing hair",
      faq: [
        { question: "How long before I see results?", answer: "Hair growth cycles take 8-12 weeks minimum. Consistency matters more than speed." },
        { question: "Can I use with shampoo on the same day?", answer: "Yes. Apply serum to dry scalp, then wash separately." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
    {
      id: "demo-hair-keto-shampoo",
      category: "hair_loss",
      name: "Scalp Reset Therapy Shampoo",
      ingredients: [
        { name: "Ketoconazole", concentration: "2%", purpose: "Scalp environment support" },
        { name: "Zinc Pyrithione", concentration: "1%", purpose: "Scalp conditioning" },
      ],
      description: "Support shampoo for buildup, flaking, and inflammatory scalp stress.",
      why: "Keeps the scalp environment cleaner and more supportive for recovery routines.",
      usage: "Use 2 to 3 times weekly based on oil and sweat load.",
      priceInr: 749,
      benefits: ["Buildup reduction", "Scalp comfort", "Wash-day support"],
      shopifyHandle: "scalp-reset-therapy-shampoo",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["shampoo", "ketoconazole", "scalp", "cleanse", "wash"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high scalp involvement" },
      suitableSkinOrHairType: ["oily scalp", "flaky scalp"],
      compatibleProducts: ["demo-hair-growth-serum"],
      incompatibleProducts: [],
      applicationMethod: "Massage into wet scalp for 1-2 minutes, then rinse thoroughly",
      quantity: "Coin-sized for full scalp",
      frequency: "2-3 times per week initially, then 1-2 times weekly for maintenance",
      targetArea: "Entire scalp",
      precautions: ["Do not use daily unless directed", "Avoid eye contact", "Discontinue if scalp irritation worsens"],
      storage: "Store in cool, dry place. Avoid freezing.",
      expectedTimeline: "Reduced flaking and better scalp feel in 1-2 weeks",
      expectedBenefit: "Cleaner scalp environment supporting growth routines",
      faq: [
        { question: "Can I use daily?", answer: "Not recommended. Start 2-3 times weekly. Daily use may disrupt natural scalp balance." },
        { question: "Is this suitable for color-treated hair?", answer: "Yes. This is a gentle cleanse and does not affect color." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
  ],
  scalp_health: [
    {
      id: "demo-scalp-balance-cleanser",
      category: "scalp_health",
      name: "Balance Scalp Cleanser",
      ingredients: [
        { name: "Selenium Sulfide", concentration: "1.5%", purpose: "Flake and oil control" },
        { name: "Zinc Compound", concentration: "1%", purpose: "Scalp soothing" },
      ],
      description: "Targeted scalp cleanser for dandruff-prone wash days.",
      why: "Helps reduce flakes and keeps oil-driven scalp irritation under better control.",
      usage: "Massage into scalp and rinse thoroughly on scheduled wash days.",
      priceInr: 699,
      benefits: ["Flake control", "Oil balance", "Scalp reset"],
      shopifyHandle: "balance-scalp-cleanser",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["cleanse", "shampoo", "dandruff", "scalp", "flakes"],
      suitableSeverity: { min: 0, max: 100, label: "All scalp concerns" },
      suitableSkinOrHairType: ["all hair types"],
      compatibleProducts: ["demo-scalp-soothe-tonic"],
      incompatibleProducts: [],
      applicationMethod: "Wet scalp, apply, massage for 1-2 minutes, rinse thoroughly",
      quantity: "Coin-sized per application",
      frequency: "2-3 times per week or as needed",
      targetArea: "Entire scalp",
      precautions: ["Avoid eye contact", "Leave on scalp only, not hair length", "Rinse completely"],
      storage: "Store upright in cool, dry place.",
      expectedTimeline: "Reduced flaking visible in 3-5 days with consistent use",
      expectedBenefit: "Calmer, flake-free scalp with better oil balance",
      faq: [
        { question: "Will this dry out my hair?", answer: "No, it targets scalp only. Keep it away from hair length." },
        { question: "How often should I use it?", answer: "2-3 times weekly initially. Adjust based on flake improvement." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
    {
      id: "demo-scalp-soothe-tonic",
      category: "scalp_health",
      name: "Calm Scalp Night Tonic",
      ingredients: [
        { name: "Panthenol", concentration: "5%", purpose: "Scalp comfort and hydration" },
        { name: "Botanical Extracts", concentration: "2%", purpose: "Soothing and anti-inflammatory" },
      ],
      description: "Leave-on tonic for itch-prone or red scalp areas.",
      why: "Supports comfort and reduces nighttime scratching triggers.",
      usage: "Apply at night on itchy or inflamed scalp partitions.",
      priceInr: 799,
      benefits: ["Itch relief", "Barrier comfort", "Night support"],
      shopifyHandle: "calm-scalp-night-tonic",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["tonic", "soothing", "night", "itch", "inflamed"],
      suitableSeverity: { min: 40, max: 100, label: "Moderate to high itch or irritation" },
      suitableSkinOrHairType: ["irritated scalp", "itch-prone scalp"],
      compatibleProducts: ["demo-scalp-balance-cleanser"],
      incompatibleProducts: [],
      applicationMethod: "Parting scalp and applying directly to affected areas with applicator",
      quantity: "As directed on label",
      frequency: "Nightly or as needed for itch relief",
      targetArea: "Itchy or inflamed scalp partitions",
      precautions: ["Do not rinse out overnight", "Avoid eye contact", "Discontinue if irritation worsens"],
      storage: "Store at room temperature in dark bottle.",
      expectedTimeline: "Reduced itch and comfort improvement within 1-2 nights",
      expectedBenefit: "Less nighttime scratching and better sleep comfort",
      faq: [
        { question: "Can I sleep with this on?", answer: "Yes, that's the intended use. Wash out in the morning." },
        { question: "Is it oily?", answer: "Minimal residue. Use on damp scalp for best results." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  dark_circles: [
    {
      id: "demo-eye-caffeine-serum",
      category: "dark_circles",
      name: "AM De-Puff Caffeine Eye Serum",
      ingredients: [
        { name: "Caffeine", concentration: "5%", purpose: "Vascular constriction and de-puffing" },
        { name: "EGCG", concentration: "2%", purpose: "Antioxidant and anti-inflammatory" },
      ],
      description: "Morning eye serum for puffiness and tired-looking under-eyes.",
      why: "Supports a fresher under-eye look and better morning recovery presentation.",
      usage: "Tap gently under the eyes each morning.",
      priceInr: 799,
      benefits: ["Puffiness control", "Morning brightness", "Light hydration"],
      shopifyHandle: "am-de-puff-caffeine-eye-serum",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["caffeine", "eye", "morning", "puffiness", "serum"],
      suitableSeverity: { min: 0, max: 100, label: "All dark circle concerns" },
      suitableSkinOrHairType: ["sensitive eye area", "all skin types"],
      compatibleProducts: ["demo-eye-retinoid-cream"],
      incompatibleProducts: [],
      applicationMethod: "Tap gently with ring finger on orbital bone and under-eye area",
      quantity: "2-3 taps or pea-sized amount",
      frequency: "Once daily in morning",
      targetArea: "Under-eye area and orbital bone",
      precautions: ["Avoid direct eye contact", "Patch test first", "Use SPF during day"],
      storage: "Store in cool, dark place. Use within 6 months of opening.",
      expectedTimeline: "Visible puffiness reduction within 5-10 minutes, cumulative improvement in 1-2 weeks",
      expectedBenefit: "Fresher, less puffy under-eye appearance in mornings",
      faq: [
        { question: "How quickly does it work?", answer: "Immediate puffiness reduction typically visible within 5-10 minutes." },
        { question: "Can I use under makeup?", answer: "Yes. Wait 1-2 minutes before applying makeup." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
    {
      id: "demo-eye-retinoid-cream",
      category: "dark_circles",
      name: "Under-Eye Repair Retinoid Cream",
      ingredients: [
        { name: "Retinol", concentration: "0.25%", purpose: "Turnover and texture support" },
        { name: "Ceramide", concentration: "3%", purpose: "Barrier support and hydration" },
      ],
      description: "Night eye cream for texture and long-term under-eye support.",
      why: "Supports smoother under-eye skin with gradual use.",
      usage: "Use on alternate nights around the orbital bone.",
      priceInr: 899,
      benefits: ["Texture support", "Night repair", "Collagen support"],
      shopifyHandle: "under-eye-repair-retinoid-cream",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["retinoid", "eye", "night", "repair", "cream"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high dark circles with texture" },
      suitableSkinOrHairType: ["mature skin", "textured eye area"],
      compatibleProducts: ["demo-eye-caffeine-serum"],
      incompatibleProducts: [],
      applicationMethod: "Dab small amount on orbital bone and gently tap until absorbed",
      quantity: "Pea-sized",
      frequency: "Every other night initially, then nightly if tolerated",
      targetArea: "Under-eye area around orbital bone",
      precautions: ["Avoid eye contact", "Do not use before SPF", "Start slowly on alternate nights"],
      storage: "Store in cool, dark place away from heat.",
      expectedTimeline: "Improved texture in 4-6 weeks, visible tone improvement in 8-12 weeks",
      expectedBenefit: "Smoother, more refined under-eye texture and tone support",
      faq: [
        { question: "When can I increase frequency?", answer: "After 2-3 weeks on alternate nights, if no irritation, try every night." },
        { question: "Can I layer with caffeine serum?", answer: "Yes. Use caffeine in AM, retinoid in PM for best results." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  beard_growth: [
    {
      id: "demo-beard-growth-serum",
      category: "beard_growth",
      name: "Beard Density Growth Serum",
      ingredients: [
        { name: "Redensyl", concentration: "0.75%", purpose: "Follicle activation" },
        { name: "Peptide Blend", concentration: "2%", purpose: "Skin-under-beard conditioning" },
      ],
      description: "Serum for patchy beard zones and density-focused routines.",
      why: "Supports consistent beard-area care where density is visibly weaker.",
      usage: "Apply daily to sparse zones and massage gently.",
      priceInr: 749,
      benefits: ["Patch support", "Density routine", "Skin-under-beard care"],
      shopifyHandle: "beard-density-growth-serum",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["beard", "growth", "serum", "patchy", "density"],
      suitableSeverity: { min: 0, max: 100, label: "All beard growth concerns" },
      suitableSkinOrHairType: ["all beard types"],
      compatibleProducts: ["demo-beard-ingrown-gel"],
      incompatibleProducts: [],
      applicationMethod: "Apply to clean, dry beard area and massage gently into skin",
      quantity: "5-10 drops or as labeled",
      frequency: "Once or twice daily",
      targetArea: "Beard line, patchy zones, skin under beard",
      precautions: ["Avoid eye area", "Use SPF if going outdoors", "Do not apply to wet beard"],
      storage: "Store in cool place away from direct sunlight.",
      expectedTimeline: "Improved skin comfort in 1-2 weeks, visible density in 8-12 weeks",
      expectedBenefit: "Denser-appearing beard with healthier underlying skin",
      faq: [
        { question: "Will this help patchiness?", answer: "Yes. Consistent use supports fuller, healthier-looking growth in sparse zones." },
        { question: "Can I use with other beard products?", answer: "Yes. Apply serum first, then other products." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
    {
      id: "demo-beard-ingrown-gel",
      category: "beard_growth",
      name: "Ingrown Control Beard Gel",
      ingredients: [
        { name: "PHA", concentration: "5%", purpose: "Gentle exfoliation" },
        { name: "Tea Tree", concentration: "2%", purpose: "Anti-inflammatory support" },
      ],
      description: "Post-shave support gel for ingrown-prone beard lines.",
      why: "Helps reduce follicle blockage and shaving-related irritation.",
      usage: "Use 2 to 3 nights per week on ingrown-prone zones.",
      priceInr: 649,
      benefits: ["Ingrown support", "Post-shave calm", "Texture reset"],
      shopifyHandle: "ingrown-control-beard-gel",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["ingrown", "shave", "gel", "beard", "night"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high ingrown/irritation concerns" },
      suitableSkinOrHairType: ["ingrown-prone skin"],
      compatibleProducts: ["demo-beard-growth-serum"],
      incompatibleProducts: [],
      applicationMethod: "Apply to clean, dry beard area and massage gently into skin",
      quantity: "Pea-sized or as labeled",
      frequency: "2-3 nights per week post-shave",
      targetArea: "Ingrown-prone beard line zones",
      precautions: ["Avoid eye area", "Do not use on active wounds", "Test patch before full application"],
      storage: "Store at room temperature in dark container.",
      expectedTimeline: "Reduced ingrown irritation within 2-3 nights of use",
      expectedBenefit: "Less ingrown-related bumps and clearer post-shave beard line",
      faq: [
        { question: "When should I use this relative to shaving?", answer: "Best used 1-2 hours after shaving on dry, clean skin." },
        { question: "Can I use daily?", answer: "Not recommended. 2-3 times weekly is optimal for prevention without over-drying." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  body_acne: [
    {
      id: "demo-body-bha-cleanser",
      category: "body_acne",
      name: "Body Clear BHA Cleanser",
      ingredients: [
        { name: "Salicylic Acid", concentration: "2%", purpose: "Pore clearing and exfoliation" },
        { name: "Botanical Extract", concentration: "1%", purpose: "Anti-inflammatory support" },
      ],
      description: "Body wash for workout-related congestion on chest, shoulders, and back.",
      why: "Supports pore clearing in sweat-heavy body zones.",
      usage: "Use during shower after sweating or workouts.",
      priceInr: 699,
      benefits: ["Body congestion control", "Post-workout support", "Pore clearing"],
      shopifyHandle: "body-clear-bha-cleanser",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["body", "cleanser", "bha", "shower", "post-workout"],
      suitableSeverity: { min: 0, max: 100, label: "All body acne severities" },
      suitableSkinOrHairType: ["oily body skin", "workout-prone skin"],
      compatibleProducts: ["demo-body-repair-lotion"],
      incompatibleProducts: [],
      applicationMethod: "Apply to wet skin in shower, massage gently, rinse thoroughly",
      quantity: "Coin-sized per application",
      frequency: "Daily or post-workout",
      targetArea: "Chest, shoulders, back, and other body acne zones",
      precautions: ["Rinse completely", "Use SPF on body if sun-exposed", "Follow with moisturizer"],
      storage: "Store in cool, dry place.",
      expectedTimeline: "Reduced congestion in 3-5 days with consistent use",
      expectedBenefit: "Clearer body skin with fewer post-workout breakouts",
      faq: [
        { question: "Can I use daily?", answer: "Yes, especially on workout days. Adjust to 3-5 times weekly if skin becomes dry." },
        { question: "Is this harsh?", answer: "No. BHA 2% is gentle enough for daily use on body." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
    {
      id: "demo-body-repair-lotion",
      category: "body_acne",
      name: "Body Barrier Repair Lotion",
      ingredients: [
        { name: "Ceramide", concentration: "3%", purpose: "Barrier repair and protection" },
        { name: "Panthenol", concentration: "2%", purpose: "Comfort and hydration" },
      ],
      description: "Light lotion for active-wash days to reduce over-drying.",
      why: "Helps keep body skin calm enough to tolerate regular acne care.",
      usage: "Apply after cleansing on dry or irritated zones.",
      priceInr: 799,
      benefits: ["Barrier support", "Dryness control", "Routine sustainability"],
      shopifyHandle: "body-barrier-repair-lotion",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["body", "moisturizer", "repair", "lotion", "barrier"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high with irritation" },
      suitableSkinOrHairType: ["dry body skin", "irritated skin"],
      compatibleProducts: ["demo-body-bha-cleanser"],
      incompatibleProducts: [],
      applicationMethod: "Apply to clean, damp skin and spread evenly",
      quantity: "Almond-sized per application",
      frequency: "Daily or after BHA wash",
      targetArea: "Body acne zones and surrounding dry areas",
      precautions: ["Use on damp skin for better absorption", "Avoid very thick application"],
      storage: "Store at room temperature.",
      expectedTimeline: "Reduced dryness and irritation within 2-3 days",
      expectedBenefit: "Sustained routine without over-drying or barrier breakdown",
      faq: [
        { question: "Do I need this if I use BHA?", answer: "Yes. BHA can dry skin, so moisturizer helps maintain tolerance." },
        { question: "Is this suitable for very oily skin?", answer: "It's light enough for most. If too heavy, use less product." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  body_odor: [
    {
      id: "demo-odor-control-body-wash",
      category: "body_odor",
      name: "Sweat Reset Antibacterial Body Wash",
      ingredients: [
        { name: "Lactic Acid", concentration: "2%", purpose: "Gentle cleansing and odor prevention" },
        { name: "Zinc Ricinoleate", concentration: "1.5%", purpose: "Odor neutralization" },
      ],
      description: "Daily body wash for sweat-heavy underarms, chest, back, and groin-adjacent outer skin.",
      why: "Helps lower sweat-film odor and keeps heat-prone skin fresher through long commute or gym days.",
      usage: "Use after commute, sport, or any heavy-sweat window. Focus on underarms, chest, and back.",
      priceInr: 649,
      benefits: ["Odor control", "Sweat-film reset", "Body freshness support"],
      shopifyHandle: "sweat-reset-antibacterial-body-wash",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["odor", "sweat", "body wash", "underarm", "freshness"],
      suitableSeverity: { min: 0, max: 100, label: "All body odor concerns" },
      suitableSkinOrHairType: ["all skin types"],
      compatibleProducts: ["demo-underarm-protect-roll-on"],
      incompatibleProducts: [],
      applicationMethod: "Apply to wet skin, massage into sweat-prone areas, rinse thoroughly",
      quantity: "Coin-sized per application",
      frequency: "Daily or post-sweat",
      targetArea: "Underarms, chest, back, and sweat-prone zones",
      precautions: ["Rinse completely", "Pat dry before antiperspirant", "Use SPF if sun-exposed"],
      storage: "Store in cool, dry place.",
      expectedTimeline: "Immediate freshness, sustained odor control with daily use",
      expectedBenefit: "Significantly reduced sweat-related body odor throughout the day",
      faq: [
        { question: "How often should I use this?", answer: "Daily or whenever you sweat heavily. Safe for regular use." },
        { question: "Does this replace antiperspirant?", answer: "No. Use this for cleansing, then apply antiperspirant separately for sweat control." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
    {
      id: "demo-underarm-protect-roll-on",
      category: "body_odor",
      name: "DryDay Underarm Protect Roll-On",
      ingredients: [
        { name: "Aluminum Chlorohydrate", concentration: "20%", purpose: "Sweat control and moisture absorption" },
        { name: "Niacinamide", concentration: "2%", purpose: "Skin conditioning and irritation prevention" },
      ],
      description: "Night roll-on for underarm sweat control and lower odor rebound by next day.",
      why: "Supports lower sweat output and less odor retention in shirts during Indian summer or commute-heavy schedules.",
      usage: "Apply on fully dry underarms at night 3 to 5 times weekly.",
      priceInr: 549,
      benefits: ["Sweat control", "Shirt freshness", "Next-day odor reduction"],
      shopifyHandle: "dryday-underarm-protect-roll-on",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["underarm", "roll-on", "sweat", "odor", "night"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high sweat and odor concerns" },
      suitableSkinOrHairType: ["high-sweat individuals"],
      compatibleProducts: ["demo-odor-control-body-wash"],
      incompatibleProducts: [],
      applicationMethod: "Roll onto completely dry underarms before bed",
      quantity: "As directed on label",
      frequency: "3-5 times weekly at night",
      targetArea: "Underarms only",
      precautions: ["Apply only to completely dry skin", "Avoid immediately after shower", "Stop if irritation develops"],
      storage: "Store at room temperature.",
      expectedTimeline: "Reduced next-day sweat and odor within first week",
      expectedBenefit: "Dramatically reduced sweat output and next-day odor retention",
      faq: [
        { question: "Can I use daily?", answer: "Not recommended. 3-5 times weekly is ideal to avoid skin irritation." },
        { question: "When should I apply it?", answer: "Before bed on completely dry skin for best sweat control overnight." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
  ],
  lip_care: [
    {
      id: "demo-lip-spf-balm",
      category: "lip_care",
      name: "Daily Shield SPF Lip Balm",
      ingredients: [
        { name: "SPF 30 (UV Filters)", concentration: "varies", purpose: "UV protection" },
        { name: "Vitamin E", concentration: "2%", purpose: "Antioxidant and hydration" },
      ],
      description: "Day balm for sun, dryness, and repeat reapplication.",
      why: "Protects against UV-linked lip darkening and daytime moisture loss.",
      usage: "Apply every morning and reapply outdoors.",
      priceInr: 349,
      benefits: ["UV protection", "Day hydration", "Pigmentation support"],
      shopifyHandle: "daily-shield-spf-lip-balm",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["lip", "spf", "day", "balm", "sun"],
      suitableSeverity: { min: 0, max: 100, label: "All lip care concerns" },
      suitableSkinOrHairType: ["all lip types"],
      compatibleProducts: ["demo-lip-repair-ointment"],
      incompatibleProducts: [],
      applicationMethod: "Apply directly to lips, reapply every 2-3 hours and after eating/drinking",
      quantity: "As needed per application",
      frequency: "Daily, multiple applications",
      targetArea: "Lips and lip border",
      precautions: ["Do not swallow", "Reapply after meals", "Use consistently for pigmentation support"],
      storage: "Store in cool place away from direct heat.",
      expectedTimeline: "Immediate UV protection, cumulative pigmentation support in 4-6 weeks",
      expectedBenefit: "Protected lips with maintained color and hydration",
      faq: [
        { question: "How often should I reapply?", answer: "Every 2-3 hours, more often if eating, drinking, or swimming." },
        { question: "Is this suitable for all seasons?", answer: "Yes. UV protection is important year-round, even in winter and indoors." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
    {
      id: "demo-lip-repair-ointment",
      category: "lip_care",
      name: "Night Repair Lip Ointment",
      ingredients: [
        { name: "Petrolatum", concentration: "80%", purpose: "Occlusive seal and hydration lock" },
        { name: "Panthenol", concentration: "5%", purpose: "Healing and comfort support" },
      ],
      description: "Occlusive night repair for cracked or peeling lips.",
      why: "Supports overnight healing and reduces morning tightness.",
      usage: "Use a thick layer before sleep.",
      priceInr: 399,
      benefits: ["Crack repair", "Occlusive seal", "Night recovery"],
      shopifyHandle: "night-repair-lip-ointment",
      tierLabel: "Clinical Booster",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["lip", "night", "ointment", "repair", "crack"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high lip damage" },
      suitableSkinOrHairType: ["dry/cracked lips"],
      compatibleProducts: ["demo-lip-spf-balm"],
      incompatibleProducts: [],
      applicationMethod: "Apply thick layer to lips before bed, do not rinse",
      quantity: "Generous layer as needed",
      frequency: "Nightly or as needed",
      targetArea: "Lips and lip border",
      precautions: ["Do not apply to active sores", "May transfer to pillowcase"],
      storage: "Store in cool place. Shelf life 12 months.",
      expectedTimeline: "Visible improvement in cracking and tightness within 1-2 nights",
      expectedBenefit: "Softer, healed lips with reduced cracking and morning tightness",
      faq: [
        { question: "Can I use during the day?", answer: "Yes, but it's thick. Best reserved for nighttime use." },
        { question: "Is it safe to ingest?", answer: "Petrolatum is non-toxic if small amounts are ingested, but avoid intentional swallowing." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  anti_aging: [
    {
      id: "demo-antioxidant-c-serum",
      category: "anti_aging",
      name: "AM Antioxidant C Serum",
      ingredients: [
        { name: "Vitamin C (L-Ascorbic Acid)", concentration: "10%", purpose: "Antioxidant and brightening" },
        { name: "Ferulic Acid", concentration: "0.5%", purpose: "Stabilization and synergy" },
      ],
      description: "Morning antioxidant serum for dullness and daily photoaging defense.",
      why: "Supports brighter-looking skin and daily environmental defense.",
      usage: "Apply in the morning before moisturizer and sunscreen.",
      priceInr: 899,
      benefits: ["Brightening", "Antioxidant defense", "AM support"],
      shopifyHandle: "am-antioxidant-c-serum",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["vitamin c", "antioxidant", "morning", "serum", "brightening"],
      suitableSeverity: { min: 0, max: 100, label: "All anti-aging concerns" },
      suitableSkinOrHairType: ["all skin types"],
      compatibleProducts: ["demo-retinoid-night-cream"],
      incompatibleProducts: [],
      applicationMethod: "Apply 2-3 drops to damp face using tapping motions",
      quantity: "2-3 drops",
      frequency: "Once daily in morning",
      targetArea: "Face, neck, and sun-exposed areas",
      precautions: ["Use SPF 30+ daily", "May cause tingling initially", "Discontinue if irritation develops"],
      storage: "Store in cool, dark place. Use within 3-6 months of opening.",
      expectedTimeline: "Brighter appearance in 1-2 weeks, cumulative anti-aging benefit in 8-12 weeks",
      expectedBenefit: "Brighter tone and better daily environmental defense",
      faq: [
        { question: "Why does my skin tingle?", answer: "Vitamin C is naturally acidic. Tingling usually subsides after first few uses." },
        { question: "Can I use with other actives?", answer: "Yes, Vitamin C is compatible with most actives. Layer based on serum texture." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
    {
      id: "demo-retinoid-night-cream",
      category: "anti_aging",
      name: "Night Renew Retinoid Cream",
      ingredients: [
        { name: "Retinol", concentration: "0.3%", purpose: "Turnover and collagen support" },
        { name: "Peptide Complex", concentration: "2%", purpose: "Firming and renewal support" },
      ],
      description: "Night cream for fine lines, texture, and long-term recovery structure.",
      why: "Supports gradual texture improvement with structured nighttime use.",
      usage: "Start 2 to 3 nights weekly and increase slowly.",
      priceInr: 999,
      benefits: ["Fine-line support", "Night renewal", "Texture care"],
      shopifyHandle: "night-renew-retinoid-cream",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["retinoid", "night", "cream", "anti-aging", "texture"],
      suitableSeverity: { min: 40, max: 100, label: "Moderate to high signs of aging" },
      suitableSkinOrHairType: ["mature skin"],
      compatibleProducts: ["demo-antioxidant-c-serum"],
      incompatibleProducts: [],
      applicationMethod: "Apply pea-sized amount on damp face and gently pat until absorbed",
      quantity: "Pea-sized",
      frequency: "2-3 nights weekly initially, then nightly if tolerated",
      targetArea: "Face, neck, and targeted fine-line areas",
      precautions: ["Start slowly", "Use SPF 30+ during day", "Do not use with other retinoids"],
      storage: "Store in cool, dark place in opaque container.",
      expectedTimeline: "Visible texture improvement in 4-6 weeks, fine-line reduction in 8-12 weeks",
      expectedBenefit: "Improved texture, reduced fine lines, and refined skin appearance",
      faq: [
        { question: "When can I increase to nightly?", answer: "After 2-3 weeks on alternate nights, if no irritation, try every night." },
        { question: "What about retinization?", answer: "Mild flaking/dryness is normal for first 1-2 weeks. Use SPF and moisturizer daily." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
  ],
  skin_dullness: [
    {
      id: "demo-brightening-c-serum",
      category: "skin_dullness",
      name: "Daily Bright Vitamin C Serum",
      ingredients: [
        { name: "Vitamin C (L-Ascorbic Acid)", concentration: "12%", purpose: "Brightening and tone support" },
        { name: "Ferulic Acid + Vitamin E", concentration: "1.5%", purpose: "Stabilization and potency" },
      ],
      description: "Morning serum for dull tone, uneven brightness, and pollution-heavy days.",
      why: "Supports visible glow, tan fade support, and better defense against outdoor stress.",
      usage: "Apply every morning after cleansing and before moisturizer plus sunscreen.",
      priceInr: 849,
      benefits: ["Glow support", "Tone support", "Pollution defense"],
      shopifyHandle: "daily-bright-vitamin-c-serum",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["dullness", "brightening", "vitamin c", "glow", "morning"],
      suitableSeverity: { min: 0, max: 100, label: "All dullness concerns" },
      suitableSkinOrHairType: ["all skin types"],
      compatibleProducts: ["demo-night-renew-lactic-serum"],
      incompatibleProducts: [],
      applicationMethod: "Apply 2-3 drops to damp face, tap until absorbed",
      quantity: "2-3 drops",
      frequency: "Once daily in morning",
      targetArea: "Face and neck",
      precautions: ["Always use SPF 30+ after", "May cause mild tingling initially"],
      storage: "Store in dark bottle in cool place. Use within 3-6 months.",
      expectedTimeline: "Noticeable glow in 1-2 weeks, cumulative brightening in 6-8 weeks",
      expectedBenefit: "Visibly brighter, more radiant complexion with better tone even",
      faq: [
        { question: "Can I use this daily?", answer: "Yes, this concentration is safe for daily use." },
        { question: "Does it help with tan?", answer: "Yes. Vitamin C supports more even tone over time." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
    {
      id: "demo-night-renew-lactic-serum",
      category: "skin_dullness",
      name: "Night Renew Lactic Serum",
      ingredients: [
        { name: "Lactic Acid", concentration: "5%", purpose: "Gentle exfoliation and renewal" },
        { name: "Panthenol", concentration: "3%", purpose: "Comfort and hydration support" },
      ],
      description: "Low-irritation night serum for rough texture and tired-looking skin.",
      why: "Helps improve texture and glow without pushing users into harsh exfoliation too fast.",
      usage: "Use 2 to 4 nights weekly on dry skin, then follow with moisturizer.",
      priceInr: 799,
      benefits: ["Texture smoothness", "Night renewal", "Dullness reset"],
      shopifyHandle: "night-renew-lactic-serum",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["lactic", "texture", "night", "dullness", "renew"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high dullness with texture" },
      suitableSkinOrHairType: ["textured skin", "dull skin"],
      compatibleProducts: ["demo-brightening-c-serum"],
      incompatibleProducts: [],
      applicationMethod: "Apply to clean, dry face and wait 5-10 minutes before moisturizer",
      quantity: "Pea-sized or as labeled",
      frequency: "2-4 nights weekly initially",
      targetArea: "Face and dull/textured zones",
      precautions: ["Use on dry skin only", "Always use SPF 30+ next day", "Do not use with other acids initially"],
      storage: "Store in cool, dark place.",
      expectedTimeline: "Improved texture in 1-2 weeks, visible glow improvement in 4-6 weeks",
      expectedBenefit: "Smoother texture and noticeably brighter, more refreshed complexion",
      faq: [
        { question: "Can I layer with other actives?", answer: "Not recommended. Use Lactic on separate nights from retinoids or other actives." },
        { question: "How quickly can I increase frequency?", answer: "After 2 weeks at 2-3 nights weekly, you can increase to 4 nights if skin tolerates." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  energy_fatigue: [
    {
      id: "demo-electrolyte-hydration-mix",
      category: "energy_fatigue",
      name: "Daily Restore Electrolyte Mix",
      ingredients: [
        { name: "Electrolytes (Sodium, Potassium, Magnesium)", concentration: "varies", purpose: "Hydration and electrolyte balance" },
        { name: "B-Vitamin Complex", concentration: "varies", purpose: "Energy and metabolism support" },
      ],
      description: "Hydration support mix for commute-heavy, sweat-heavy, or screen-heavy days.",
      why: "Supports hydration rhythm and lowers energy dips caused by dehydration and long work blocks.",
      usage: "Use once in the first half of the day or after heavy sweat exposure.",
      priceInr: 499,
      benefits: ["Hydration support", "Energy steadiness", "Heat-day recovery"],
      shopifyHandle: "daily-restore-electrolyte-mix",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["energy", "fatigue", "electrolyte", "hydration", "daytime"],
      suitableSeverity: { min: 0, max: 100, label: "All energy concerns" },
      suitableSkinOrHairType: ["n/a"],
      compatibleProducts: ["demo-magnesium-sleep-support"],
      incompatibleProducts: [],
      applicationMethod: "Mix with 250ml water and drink, or mix in morning beverage",
      quantity: "One sachet per serving",
      frequency: "Once daily, typically in morning or post-workout",
      targetArea: "Internal hydration support",
      precautions: ["Do not exceed recommended dose", "Monitor sodium intake on other days"],
      storage: "Store in cool, dry place. Keep sachets in sealed container.",
      expectedTimeline: "Immediate hydration boost, sustained energy improvement with daily use",
      expectedBenefit: "Better daytime hydration and more stable energy levels",
      faq: [
        { question: "When is best time to use?", answer: "Morning or immediately after sweat exposure. Avoid close to bedtime." },
        { question: "Is this suitable for pre-workout?", answer: "Yes, but use 30-60 minutes before training for absorption." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
    {
      id: "demo-magnesium-sleep-support",
      category: "energy_fatigue",
      name: "Night Calm Magnesium Support",
      ingredients: [
        { name: "Magnesium Glycinate", concentration: "varies", purpose: "Sleep quality and relaxation support" },
        { name: "L-Theanine", concentration: "varies", purpose: "Calm and focus" },
      ],
      description: "Night support for users whose next-day fatigue tracks with poor sleep quality.",
      why: "Supports deeper sleep readiness and more stable next-day recovery rhythm.",
      usage: "Take in the evening after dinner based on tolerance and medical suitability.",
      priceInr: 699,
      benefits: ["Sleep support", "Recovery rhythm", "Night calm"],
      shopifyHandle: "night-calm-magnesium-support",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["sleep", "magnesium", "fatigue", "night", "recovery"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high fatigue with poor sleep" },
      suitableSkinOrHairType: ["n/a"],
      compatibleProducts: ["demo-electrolyte-hydration-mix"],
      incompatibleProducts: [],
      applicationMethod: "Mix with warm water or milk and drink 30-60 minutes before bed",
      quantity: "One serving as directed",
      frequency: "Once daily in evening",
      targetArea: "Internal sleep and recovery support",
      precautions: ["Not suitable if taking certain medications", "Consult doctor if pregnant or breastfeeding"],
      storage: "Store in cool, dry place. Shake well if powder.",
      expectedTimeline: "Improved sleep quality within 3-5 nights, sustained next-day energy after 1-2 weeks",
      expectedBenefit: "Deeper sleep and significantly better next-day energy and recovery",
      faq: [
        { question: "When should I take this?", answer: "30-60 minutes before bed, after dinner." },
        { question: "Can I use with other supplements?", answer: "Generally yes, but consult healthcare provider if on other medications." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  fitness_recovery: [
    {
      id: "demo-recovery-protein-blend",
      category: "fitness_recovery",
      name: "Post-Training Recovery Protein",
      ingredients: [
        { name: "Whey Protein Isolate", concentration: "25g per serving", purpose: "Muscle repair and recovery" },
        { name: "Digestive Enzymes", concentration: "varies", purpose: "Digestion and absorption support" },
      ],
      description: "Fast post-workout protein support for soreness, under-recovery, and missed protein targets.",
      why: "Helps close common Indian men recovery gaps where training is regular but protein timing is weak.",
      usage: "Use within 60 minutes after training or as a high-protein snack replacement.",
      priceInr: 1499,
      benefits: ["Protein recovery", "Muscle repair support", "Post-workout convenience"],
      shopifyHandle: "post-training-recovery-protein",
      tierLabel: "Core Protocol",
      suitableLevels: ["beginner", "intermediate", "advanced"],
      keywords: ["protein", "post-workout", "recovery", "fitness", "muscle"],
      suitableSeverity: { min: 0, max: 100, label: "All fitness recovery needs" },
      suitableSkinOrHairType: ["n/a"],
      compatibleProducts: ["demo-recovery-magnesium-gel"],
      incompatibleProducts: [],
      applicationMethod: "Mix 25-30g with 200-300ml water or milk, drink immediately",
      quantity: "One serving per post-workout",
      frequency: "Immediately post-workout, up to once daily",
      targetArea: "Internal muscle recovery",
      precautions: ["Check for lactose intolerance if whey", "Stay hydrated"],
      storage: "Store in cool, dry place. Sealed container after opening.",
      expectedTimeline: "Immediate post-workout protein delivery, cumulative recovery benefit within 1-2 weeks",
      expectedBenefit: "Better muscle recovery and reduced next-day soreness",
      faq: [
        { question: "When is the best time to take this?", answer: "Within 60 minutes post-workout for best recovery support." },
        { question: "Can I use as a meal replacement?", answer: "Better as supplement. Combine with carbs and real food for complete nutrition." },
      ],
      evidenceLevel: "clinical",
      version: "1.0.0",
    },
    {
      id: "demo-recovery-magnesium-gel",
      category: "fitness_recovery",
      name: "Soreness Relief Recovery Gel",
      ingredients: [
        { name: "Magnesium", concentration: "varies", purpose: "Muscle relaxation and soreness support" },
        { name: "Arnica + Cooling Botanicals", concentration: "3%", purpose: "Comfort and cooling sensation" },
      ],
      description: "Topical support for lower-body or upper-body soreness after training or sport.",
      why: "Supports better next-day comfort so users can stay consistent instead of skipping sessions.",
      usage: "Massage onto sore muscle groups after shower or before bed.",
      priceInr: 599,
      benefits: ["Soreness support", "Comfort recovery", "Training consistency"],
      shopifyHandle: "soreness-relief-recovery-gel",
      tierLabel: "Clinical Booster",
      suitableLevels: ["intermediate", "advanced"],
      keywords: ["soreness", "recovery", "gel", "muscle", "night"],
      suitableSeverity: { min: 30, max: 100, label: "Moderate to high post-workout soreness" },
      suitableSkinOrHairType: ["n/a"],
      compatibleProducts: ["demo-recovery-protein-blend"],
      incompatibleProducts: [],
      applicationMethod: "Apply generously and massage into sore muscles for 2-3 minutes",
      quantity: "Almond-sized or as needed",
      frequency: "Post-workout or as needed",
      targetArea: "Sore muscle groups",
      precautions: ["Avoid broken skin", "Do not use before intense heat therapy"],
      storage: "Store at room temperature in sealed tube.",
      expectedTimeline: "Immediate cooling sensation, reduced soreness perception within hours",
      expectedBenefit: "Better next-day comfort and improved training consistency",
      faq: [
        { question: "How quickly does it work?", answer: "Cooling sensation immediate, soreness relief within 30-60 minutes." },
        { question: "Can I use daily?", answer: "Yes, can be used post-training as often as needed." },
      ],
      evidenceLevel: "established",
      version: "1.0.0",
    },
  ],
  hairCare: [],
  skinCare: [],
  beardCare: [],
  bodyCare: [],
  healthCare: [],
  fitness: [],
  fragrance: [],
};

clinicalDemoProductCatalog.hairCare = clinicalDemoProductCatalog.hair_loss;
clinicalDemoProductCatalog.skinCare = clinicalDemoProductCatalog.acne;
clinicalDemoProductCatalog.beardCare = clinicalDemoProductCatalog.beard_growth;
clinicalDemoProductCatalog.bodyCare = clinicalDemoProductCatalog.body_acne;
clinicalDemoProductCatalog.healthCare = clinicalDemoProductCatalog.dark_circles;
clinicalDemoProductCatalog.fitness = clinicalDemoProductCatalog.fitness_recovery;
clinicalDemoProductCatalog.fragrance = clinicalDemoProductCatalog.lip_care;

export function getClinicalDemoProducts(category: CategoryId) {
  return clinicalDemoProductCatalog[category] || [];
}

export function pickClinicalDemoProduct(category: CategoryId, taskText: string, level: ProtocolToleranceMode) {
  const products = getClinicalDemoProducts(category).filter((product) => product.suitableLevels.includes(level));
  if (products.length === 0) return null;

  const haystack = taskText.toLowerCase();
  const scored = products.map((product) => ({
    product,
    score: product.keywords.reduce((sum, keyword) => sum + (haystack.includes(keyword.toLowerCase()) ? 1 : 0), 0),
  }));
  scored.sort((left, right) => right.score - left.score);
  return scored[0]?.product || products[0] || null;
}